import { FormEvent, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Input from "@/components/elements/Input";

import { Container, Content, Banner, Button } from "./styles";

const Home: NextPage = () => {
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");

  async function handleSubmit(event: FormEvent) {
    event.preventDefault();

    const data = {
      email,
      password,
    };

    // await signIn(data);
  }

  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Banner />
        <Content>
          <form onSubmit={handleSubmit}>
            <Input
              name="username"
              placeholder="Seu usuário"
              label="Usuário:"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <Input
              name="password"
              type="password"
              placeholder="Sua senha"
              label="Senha:"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />

            <Button type="submit">Acessar</Button>
          </form>
        </Content>
      </Container>
    </>
  );
};

export default Home;
